language: scala

jdk:
- oraclejdk8
scala:
- 2.12.8
- 2.11.12


stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork


jobs:
  include:
    - env: TEST="test"
      script: sbt +test
    - stage: release
      script: sbt ci-release

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_install:
  - git fetch --tags
